services:
  ubuntu_closest:
    image: ubuntu:14.04  # Use Ubuntu 14.04 instead of 12.04
    container_name: ubuntu_closest_container
    command: sleep infinity
    tty: true
    stdin_open: true
    platform: linux/amd64
    volumes:
      - ./data:/data
    networks:
      - default
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    privileged: true  # 🔥 Full privileges
